// Regenerates firmware/tock/tock_sprites.h from Tock's poses, drawn in a sketchbook that isn't in
// the repo (lab/tock.js, which git ignores). tock_sprites.h is checked in: builds don't need this.
// Run: node firmware/gen-sprites.js
const fs = require('fs');
const path = require('path');

const src = fs.readFileSync(path.join(__dirname, '..', 'lab', 'tock.js'), 'utf8');
const { TOCK, poses, poseNotes } = new Function(
  src.slice(0, src.indexOf('function drawGrid')) + 'return { TOCK, poses, poseNotes };',
)();

const rgb565 = (hex) => {
  const n = parseInt(hex.slice(1), 16);
  const v = (((n >> 16) & 0xf8) << 8) | (((n >> 8) & 0xfc) << 3) | ((n & 0xff) >> 3);
  return '0x' + v.toString(16).padStart(4, '0').toUpperCase();
};

const names = Object.keys(poses);
const H = Math.max(...names.map((k) => poses[k].length));
const out = [
  '// tock_sprites.h: generated by firmware/gen-sprites.js from tock.js. Do not edit by hand.',
  "// '#' = body, anything else = transparent (eye and mouth holes included).",
  '#pragma once',
  '#include <stdint.h>',
  '',
  `constexpr uint32_t TOCK_BODY_RGB = 0x${TOCK.body.slice(1)};  // ${rgb565(TOCK.body)} in RGB565`,
  `constexpr int TOCK_W = ${TOCK.w}, TOCK_MAX_H = ${H};`,
  '',
  'enum TockPose { ' + names.map((k) => `POSE_${k.toUpperCase()}`).join(', ') + ', POSE_COUNT };',
  '',
  'struct TockSprite { uint8_t h; const char* rows[TOCK_MAX_H]; };',
  '',
  'const TockSprite TOCK_POSES[POSE_COUNT] = {',
];
for (const k of names) {
  const g = poses[k];
  out.push(`  { ${g.length}, {  // ${k}: ${poseNotes[k]}`, ...g.map((r) => `    "${r}",`), '  } },');
}
out.push('};', '');
fs.writeFileSync(path.join(__dirname, 'tock', 'tock_sprites.h'), out.join('\n'));
console.log(`wrote ${names.length} poses`);
